version: "3.8"
services:
    ivsapi:
        image: 401895683222.dkr.ecr.us-east-1.amazonaws.com/ivsapi:latest
        networks:
          ivsnetwork:
            ipv4_address: 10.6.0.7
        environment:
          - PORT=3000
          - TOKEN_SECRET="videostuff"
          - MONGOURL=mongodb://ivsmongodb:27017/ivsdemo
    ivsnginx:
        restart: always
        image: 401895683222.dkr.ecr.us-east-1.amazonaws.com/ivsnginx:latest
        ports:
            - "80:80"
        networks:
          ivsnetwork:
            ipv4_address: 10.6.0.8
    ivsmongodb:
        image: mongo
        ports:
            - "27017:27017"
        restart: unless-stopped
        networks:
          ivsnetwork:
            ipv4_address: 10.6.0.9
networks:
  ivsnetwork:
      driver: bridge
      ipam:
        config:
            - subnet: 10.6.0.0/16