name: IVS Demo Webapp Pipeline

on:
  push:
    branches: [ style-frontend ]

jobs:
  update-webapp:
    name: Deploy app in server
    runs-on: ubuntu-latest
      
    steps:
    - name: Pull the latest changes of the webapp
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.WEBAPP_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        password: ${{ secrets.EC2_PASSWORD }}
        target: /home/${{ secrets.EC2_USERNAME }}
        script: |
          cd ivsdemo
          git pull
          git checkout style-frontend
          git pull 

      
    - name: Install the new files into nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.WEBAPP_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        password: ${{ secrets.EC2_PASSWORD }}
        target: /home/${{ secrets.EC2_USERNAME }}
        script: |
          cd ivsdemo
          sudo cp webapp/* /var/www/html/ -vf